[feature #41584931] I reverted CrudService.java to one of the oldest approaches we used (JTA managed). I also changed the way (reverted) HumanCRUDHuman.java was persisting data through a hack. persistence.xml is now JTA CMP based. This too was rolled back to an old state. pom has some minor changes. Unfortunately I was unable to provide off the shelf configuration for the tomcat's webapps/ROOT directory deletion. This is because the maven clean plugin does not support custom maven properties(AFAIK).
These exceptions were fixed:

Caused by: javax.ejb.EJBTransactionRolledbackException: The transaction has been marked rollback only because the bean encountered a non-application exception :org.apache.openjpa.persistence.PersistenceException : Column 'T3.HUMANID' is either not in any table in the FROM list or appears within a join specification and is outside the scope of the join specification or appears in a HAVING clause and is not in the GROUP BY list. If this is a CREATE or ALTER TABLE  statement then 'T3.HUMANID' is not a column in the target table. {SELECT t0.humanId, t5.humanId, t5.displayName, t6.humanId, t6.clearance, t6.humanAlive, t7.humanId, t7.displayName FROM HumansNetPeople t0 LEFT OUTER JOIN HumansNet t5 ON t0.humanId = t5.humanId LEFT OUTER JOIN Human t6 ON t5.humanId = t6.humanId LEFT OUTER JOIN HumansNet t7 ON t6.humanId = t7.humanId WHERE (t0.humanId IN (SELECT t3.humanId FROM HumansNetPeople t1 JOIN HumansNetPeople t2 ON (1 = 1) INNER JOIN HumansNetPeople_HumansNetPeople t4 ON t3.humanId = t4.HUMANSNETPEOPLE_HUMANID, HumansNetPeople t3 WHERE (t2.humanId = ? AND t4.HUMANSNETPEOPLES_HUMANID = t2.humanId)))} [code=-1, state=42X04]
	at org.apache.openejb.core.ivm.BaseEjbProxyHandler.convertException(BaseEjbProxyHandler.java:345) [openejb-core-4.5.0.jar:4.5.0]
	at org.apache.openejb.core.ivm.BaseEjbProxyHandler.invoke(BaseEjbProxyHandler.java:283) [openejb-core-4.5.0.jar:4.5.0]
	at $Proxy133.findWithNamedQuery(Unknown Source) [na:na]
	at ai.ilikeplaces.logic.crud.unit.RHumansNetPeople.doDirtyRHumansBefriends(RHumansNetPeople.java:47) [RHumansNetPeople.class:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [na:1.6.0_37]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) [na:1.6.0_37]

These exceptions are still happening:

When reaching the profile page after a new signup(most probably due to dependency conflicts when trying to convert html nodes into email (text) format) -

http-bio-8080-exec-4|2012-12-31 18:25:17,035|EXCEPTION|AbstractWidgetListener.java:204>FATAL ERROR IN WIDGET. THIS SHOULD NOT HAPPEN DETAILS AS FOLLOWS:
page:DocWall
appendToElement: privateEventDeleteWall38
humanId: yureka80@ilikeplaces.com

org.apache.xml.serializer.utils.WrappedRuntimeException: org.apache.xml.serializer.ToXMLSAXHandler cannot be cast to org.apache.xml.serializer.SerializationHandler
	at org.apache.xml.serializer.SerializerFactory.getSerializer(SerializerFactory.java:179) [serializer.jar:2.7.1]
	at org.apache.xalan.transformer.TransformerIdentityImpl.createResultContentHandler(TransformerIdentityImpl.java:260) [xalan-2.7.1.jar:na]
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:330) [xalan-2.7.1.jar:na]
	at ai.ilikeplaces.util.HTMLDocParser.convertNodeToHtml(HTMLDocParser.java:51) [HTMLDocParser.class:na]
	at ai.ilikeplaces.logic.Listeners.widgets.WallWidgetPrivateEvent.fetchToEmail(WallWidgetPrivateEvent.java:222) [WallWidgetPrivateEvent.class:na]
	at ai.ilikeplaces.logic.Listeners.widgets.WallWidgetPrivateEvent.init(WallWidgetPrivateEvent.java:99) [WallWidgetPrivateEvent.class:na]
	at ai.ilikeplaces.util.AbstractWidgetListener.<init>(AbstractWidgetListener.java:201) [AbstractWidgetListener.class:na]
	at ai.ilikeplaces.logic.Listeners.widgets.WallWidget.<init>(WallWidget.java:52) [WallWidget.class:na]
	at ai.ilikeplaces.logic.Listeners.widgets.WallWidgetPrivateEvent.<init>(WallWidgetPrivateEvent.java:84) [WallWidgetPrivateEvent.class:na]

~Port Hobbits To Old Persistence Strategy and Fork The Original For NoSQL Testing