[feature #25702299] Port Components to Remote Components To Support Distributed Architectures - Very unstable commit. Details as follows:
### Basic Hotspot Search On Home Page Map - Encountered Below Exception

http-8080-2|2012-02-29 17:43:41,593|EXCEPTION:74>{}

java.lang.NullPointerException: SORRY! A NPE OCCURRED. PLEASE CHECK THE CALLER O
F THIS METHOD TO FIND OUT WHERE THE NPE ACTUALLY TOOK PLACE.
        at ai.ilikeplaces.util.LogNull.logThrow(LogNull.java:52) [LogNull.class:
na]
        at ai.ilikeplaces.logic.crud.DB.getHumanCrudPrivateEventLocal(DB.java:19
4) [DB.class:na]

### No errors on openejb.log

### Configured Initial Context to support remote connection.

Feb 29, 2012 6:13:32 PM org.apache.openejb.client.StickyConnectionStrategy conne
ct
WARNING: Failover: Cannot connect to server(s): ejbd://127.0.0.1:4201 Exception:
 Cannot connect to server 'ejbd://127.0.0.1:4201'.  Check that the server is sta
rted and that the specified serverURL is correct..  Trying next.
http-8080-6|2012-02-29 18:13:32,687|ai.ilikeplaces.logic.crud.DB:193>SORRY! I EN
COUNTERED AN NAMING EXCEPTION WHILE DOING A CONTEXT OPERATION.

javax.naming.NamingException: Cannot lookup '/DBLocal'.
        at org.apache.openejb.client.JNDIContext.lookup(JNDIContext.java:224) [o
penejb-client-3.1.4.jar:3.1.4]
        at javax.naming.InitialContext.lookup(InitialContext.java:392) [na:1.6.0
_16]
        at ai.ilikeplaces.logic.crud.DB.getHumanCrudPrivateEventLocal(DB.java:19
1) [DB.class:na]

### Tomcat needs this : http://127.0.0.1:8080/openejb/ejb as the provider URL
### This eliminated part of the exception and gave the following:

http-8080-1|2012-02-29 18:27:42,125|ai.ilikeplaces.logic.crud.DB:193>SORRY! I EN
COUNTERED AN NAMING EXCEPTION WHILE DOING A CONTEXT OPERATION.

javax.naming.NameNotFoundException: /DBLocal does not exist in the system.  Chec
k that the app was successfully deployed.
        at org.apache.openejb.client.JNDIContext.lookup(JNDIContext.java:261) [o
penejb-client-3.1.4.jar:3.1.4]
        at javax.naming.InitialContext.lookup(InitialContext.java:392) [na:1.6.0
_16]
        at ai.ilikeplaces.logic.crud.DB.getHumanCrudPrivateEventLocal(DB.java:19
1) [DB.class:na]
        at ai.ilikeplaces.logic.Listeners.widgets.DownTownHeatMap$5$1.<init>(Dow
nTownHeatMap.java:320) [DownTownHeatMap$5$1.class:na]

### openejb.log indicates that despite the class name, the bean was deployed as <classname>Remote (Class name is DBLocal)

2012-02-29 18:27:19,453 - INFO  - Jndi(name=DBRemote) --> Ejb(deployment-id=DB)

### Added DBRemote interface, implemented. Modified lookup in DB.java to use DBRemote instead of DBLocal

### Remote lookup of DBRemote successful. Not porting other classes to seperate interfaces until functionality is proven to be corrent.
### Hence, doing a string replace of "Local" to "Remote" during look up, leaving classnames untouched but just changing annotations to @Remote of the <classname>Local classes.

### Worked. Got a NPE on return. Beans were not serialized. Marking all of them to be serializable. Guessiing this is the reason.
### This was not the reason. openejb.log reported "Couldn't write EjbResponse to output stream" on ReturnVal. Made it serializable. Exception below:

2012-02-29 18:47:29,984 - FATAL - Couldn't write EjbResponse to output stream
java.io.NotSerializableException: ai.ilikeplaces.util.ReturnImpl

### Worked!

### Checking login.

### Got Exception:

javax.ejb.EJBException: Unknown Container Exception: java.rmi.RemoteException: E
rror while communicating with server: ; nested exception is:
        java.lang.IllegalArgumentException: Object is not serializable: ai.ilike
places.logic.validators.unit.HumanId

### Refactored SingletonHashingFace to SingletonHashingRemote
### Some classes were using SIngletonHashing clases static methods. Removed this and pointed them to DB.java.

### Worked!

### Checking Sign Up - Below exception is still unresolved.

javax.ejb.EJBException: Unknown Container Exception: java.rmi.RemoteException: E
rror while communicating with server: ; nested exception is:
        java.lang.IllegalArgumentException: Object is not serializable: com.goog
le.gdata.data.geo.impl.W3CPoint
        at org.apache.openejb.client.EJBObjectHandler._invoke(EJBObjectHandler.j
ava:190) [openejb-client-3.1.4.jar:3.1.4]
        at org.apache.openejb.client.EJBInvocationHandler.invoke(EJBInvocationHa
ndler.java:118) [openejb-client-3.1.4.jar:3.1.4]
        at org.apache.openejb.client.proxy.Jdk13InvocationHandler.invoke(Jdk13In
vocationHandler.java:52) [openejb-client-3.1.4.jar:3.1.4]
        at $Proxy142.cPrivateLocation(Unknown Source) [na:na]
        at ai.ilikeplaces.util.UserIntroduction.createIntroData(UserIntroduction
.java:16) [UserIntroduction.class:na]
        at ai.ilikeplaces.logic.Listeners.widgets.DownTownHeatMap$3.handleEvent(
DownTownHeatMap.java:217) [DownTownHeatMap$3.class:na]